[project]
name = "rosa-ottimale"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "pandas>=2.3.2",
    "pulp[open-py]>=3.3.0",
]
